name: Auto Push Changes

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
      
    - name: Test
      run: npm test --if-present
      
    - name: Commit and push if there are changes
      run: |
        git config --local user.email 'action@github.com'
        git config --local user.name 'GitHub Action'
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m 'Auto commit by GitHub Actions'
        git push
